### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by domzymonz** [PrismarineJS/bedrock-protocol#123]
When running this code
```js
const bedrock = require('bedrock-protocol')
console.log("test")
const client = bedrock.createClient({
    host: "104.128.60.187",   // optional
    port: 25565,         // optional, default 19132
    username: 'QuenchSqueal',   // the username you want to join as, optional if online mode
    offline: false,       // optional, default false. if true, do not login with Xbox Live. You will not be asked to sign-in if set to true.
    // Optional for some servers which verify the title ID:
    // authTitle: bedrock.title.MinecraftNintendoSwitch
})
```
this error is raised
```
XboxReplayError: Request failed with status code 401
    at Object.internal (C:\Users\it-admin\Documents\JS\node_modules\@xboxreplay\errors\dist\index.js:33:77)
    at C:\Users\it-admin\Documents\JS\node_modules\@xboxreplay\xboxlive-auth\dist\core\xboxlive\index.js:79:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async XboxTokenManager.getXSTSToken (C:\Users\it-admin\Documents\JS\node_modules\bedrock-protocol\src\client\tokens.js:425:18)
    at async retry.msa.forceRefresh (C:\Users\it-admin\Documents\JS\node_modules\bedrock-protocol\src\client\authFlow.js:126:24)
    at async retry (C:\Users\it-admin\Documents\JS\node_modules\bedrock-protocol\src\client\authFlow.js:27:14)
    at async MsAuthFlow.getXboxToken (C:\Users\it-admin\Documents\JS\node_modules\bedrock-protocol\src\client\authFlow.js:116:14)
    at async retry.xbl.forceRefresh (C:\Users\it-admin\Documents\JS\node_modules\bedrock-protocol\src\client\authFlow.js:143:22)
    at async retry (C:\Users\it-admin\Documents\JS\node_modules\bedrock-protocol\src\client\authFlow.js:27:14)
    at async MsAuthFlow.getMinecraftToken (C:\Users\it-admin\Documents\JS\node_modules\bedrock-protocol\src\client\authFlow.js:142:14) {
  __XboxReplay__: true,
  details: { statusCode: 500, reason: 'INTERNAL_SERVER_ERROR' }
}
(node:19296) UnhandledPromiseRejectionWarning: XboxReplayError: Request failed with status code 401
    at Object.internal (C:\Users\it-admin\Documents\JS\node_modules\@xboxreplay\errors\dist\index.js:33:77)
    at C:\Users\it-admin\Documents\JS\node_modules\@xboxreplay\xboxlive-auth\dist\core\xboxlive\index.js:79:32
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async XboxTokenManager.getXSTSToken (C:\Users\it-admin\Documents\JS\node_modules\bedrock-protocol\src\client\tokens.js:425:18)
    at async retry.msa.forceRefresh (C:\Users\it-admin\Documents\JS\node_modules\bedrock-protocol\src\client\authFlow.js:126:24)
    at async retry (C:\Users\it-admin\Documents\JS\node_modules\bedrock-protocol\src\client\authFlow.js:27:14)
    at async MsAuthFlow.getXboxToken (C:\Users\it-admin\Documents\JS\node_modules\bedrock-protocol\src\client\authFlow.js:116:14)
    at async retry.xbl.forceRefresh (C:\Users\it-admin\Documents\JS\node_modules\bedrock-protocol\src\client\authFlow.js:143:22)
    at async retry (C:\Users\it-admin\Documents\JS\node_modules\bedrock-protocol\src\client\authFlow.js:27:14)
    at async MsAuthFlow.getMinecraftToken (C:\Users\it-admin\Documents\JS\node_modules\bedrock-protocol\src\client\authFlow.js:142:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:19296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate 
the Node.js process with a non-zero exit code.
```

I don't really know what to do.

**Comment by extremeheat** [comment]
Uncomment the authTitle line.

**Comment by domzymonz** [comment]
Works, thanks!
