### ISSUE TITLE
Package in NPM registry not found

### ISSUE THREAD

**Issue by jarne** [PrismarineJS/bedrock-protocol#21]
When I'm trying to run `npm install pocket-minecraft-protcol` like described in the README.md, it shows an error that the package does not exist in NPM registry.

Console output:
```
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "install" "pocket-minecraft-protcol"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/pocket-minecraft-protcol
npm ERR! 404 
npm ERR! 404  'pocket-minecraft-protcol' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jarne/.npm/_logs/2017-04-15T10_17_07_458Z-debug.log
```

Error log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.9.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'pocket-minecraft-protcol' ]
2 info using npm@4.2.0
3 info using node@v7.9.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData pocket-minecraft-protcol
8 silly fetchNamedPackageData pocket-minecraft-protcol
9 silly mapToRegistry name pocket-minecraft-protcol
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'pocket-minecraft-protcol',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'pocket-minecraft-protcol',
12 silly mapToRegistry   name: 'pocket-minecraft-protcol',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/pocket-minecraft-protcol
14 verbose request uri https://registry.npmjs.org/pocket-minecraft-protcol
15 verbose request no auth needed
16 info attempt registry request try #1 at 12:17:06
17 verbose request id 0c43b0f07c4256b6
18 http request GET https://registry.npmjs.org/pocket-minecraft-protcol
19 http 404 https://registry.npmjs.org/pocket-minecraft-protcol
20 verbose headers { 'content-type': 'application/json',
20 verbose headers   'cache-control': 'max-age=0',
20 verbose headers   'content-length': '2',
20 verbose headers   'accept-ranges': 'bytes',
20 verbose headers   date: 'Sat, 15 Apr 2017 10:17:09 GMT',
20 verbose headers   via: '1.1 varnish',
20 verbose headers   age: '0',
20 verbose headers   connection: 'keep-alive',
20 verbose headers   'x-served-by': 'cache-fra1226-FRA',
20 verbose headers   'x-cache': 'MISS',
20 verbose headers   'x-cache-hits': '0',
20 verbose headers   'x-timer': 'S1492251429.786781,VS0,VE721',
20 verbose headers   vary: 'Accept-Encoding' }
21 silly get cb [ 404,
21 silly get   { 'content-type': 'application/json',
21 silly get     'cache-control': 'max-age=0',
21 silly get     'content-length': '2',
21 silly get     'accept-ranges': 'bytes',
21 silly get     date: 'Sat, 15 Apr 2017 10:17:09 GMT',
21 silly get     via: '1.1 varnish',
21 silly get     age: '0',
21 silly get     connection: 'keep-alive',
21 silly get     'x-served-by': 'cache-fra1226-FRA',
21 silly get     'x-cache': 'MISS',
21 silly get     'x-cache-hits': '0',
21 silly get     'x-timer': 'S1492251429.786781,VS0,VE721',
21 silly get     vary: 'Accept-Encoding' } ]
22 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/pocket-minecraft-protcol
22 silly fetchPackageMetaData     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:282:14)
22 silly fetchPackageMetaData     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:212:14)
22 silly fetchPackageMetaData     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:186:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:194:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1081:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1001:12)
22 silly fetchPackageMetaData  error for pocket-minecraft-protcol { Error: Registry returned 404 for GET on https://registry.npmjs.org/pocket-minecraft-protcol
22 silly fetchPackageMetaData     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:12)
22 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:282:14)
22 silly fetchPackageMetaData     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:212:14)
22 silly fetchPackageMetaData     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:186:22)
22 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:194:7)
22 silly fetchPackageMetaData     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1081:10)
22 silly fetchPackageMetaData     at emitOne (events.js:96:13)
22 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
22 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1001:12)
22 silly fetchPackageMetaData   pkgid: 'pocket-minecraft-protcol',
22 silly fetchPackageMetaData   statusCode: 404,
22 silly fetchPackageMetaData   code: 'E404' }
23 silly rollbackFailedOptional Starting
24 silly rollbackFailedOptional Finishing
25 silly runTopLevelLifecycles Finishing
26 silly install printInstalled
27 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/pocket-minecraft-protcol
27 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:304:12)
27 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:282:14)
27 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:212:14)
27 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:186:22)
27 verbose stack     at emitTwo (events.js:106:13)
27 verbose stack     at Request.emit (events.js:194:7)
27 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1081:10)
27 verbose stack     at emitOne (events.js:96:13)
27 verbose stack     at Request.emit (events.js:191:7)
27 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1001:12)
28 verbose statusCode 404
29 verbose pkgid pocket-minecraft-protcol
30 verbose cwd /Users/jarne/Downloads
31 error Darwin 16.5.0
32 error argv "/usr/local/Cellar/node/7.9.0/bin/node" "/usr/local/bin/npm" "install" "pocket-minecraft-protcol"
33 error node v7.9.0
34 error npm  v4.2.0
35 error code E404
36 error 404 Registry returned 404 for GET on https://registry.npmjs.org/pocket-minecraft-protcol
37 error 404
38 error 404 'pocket-minecraft-protcol' is not in the npm registry.
39 error 404 You should bug the author to publish it (or use the name yourself!)
40 error 404 Note that you can also install from a
41 error 404 tarball, folder, http url, or git url.
42 verbose exit [ 1, true ]
```

**Comment by ghost** [comment]
You're missing the o in protocol

**Comment by jarne** [comment]
Sorry, didn't saw that, but the o is also missing in the readme and I just copied it.

**Comment by ghost** [comment]
No problem, thanks for letting me know.
