### ISSUE TITLE
Read error for undefined : Missing characters in string, found size is 100 expected size was 195

### ISSUE THREAD

**Issue by squeaky2137** [PrismarineJS/bedrock-protocol#214]
When trying to join a server i get the error

While decoding 9e0116616e696d6174696f6e2e707269736f6e732e62616e6716616e696d6174696f6e2e707269736f6e732e62616e6716616e696d6174696f6e2e707269736f6e732e62616e670000000012707269736f6e732e636f6e74726f6c6c6572000000000107
PartialReadError: Read error for undefined : Missing characters in string, found size is 100 expected size was 195

ik it probs has to do with custom plugins etc but this stops the bot from joining the server even though the bot emits the spawn event

**Comment by extremeheat** [comment]
You need to provide more information such as server/client version

**Comment by squeaky2137** [comment]
Sorry, Version is 1.18.30 bedrock i believe ( newest bedrock )

server details are
ecpehub.net
19132

so you can also see, it is online mode too.

I am also running version 3.13.0 of the bedrock-protocol

**Comment by frizib** [comment]
I had a similar one. This is because of a plugin that changes values in statistics

**Comment by extremeheat** [comment]
Can you provide the whole stack trace? 

It's possible the server is sending an invalid packet and we crash or the protocol fields we have are incorrect (but vanilla passes CI for some reason). I believe U9G pointed something out wrt the recipes packet, possibly related

These errors can also be ignored if you're not interested in the packet by handling the error event

**Comment by squeaky2137** [comment]
Sorry, for long wait but here is the entire stack trace 

joined
spawned
While decoding 9e0117616e696d6174696f6e2e6f707a6575732e776561706f6e17616e696d6174696f6e2e6f707a6575732e776561706f6e17616e696d6174696f6e2e6f707a6575732e776561706f6e00000000116f707a6575732e636f6e74726f6c6c6572000000000105
While decoding fe5e240b40344d5c17ce0b0752d60ec59f784531586a21553dd08cf568face2477a768b9acbd5a4bd44be12b4ca2f2955668c8ebab38943c3fe83283902f2abe5029ef9ca6fc190f316e6de559c619344193c31a46c697645913e0f3afda14b9dd86967e6cc7cbb7b139952214a800a8019d1560e50f740aef61b032399fba43a67b2c580d5f3747f47896a4b4301712aef0d10e45f832da6225fb5ec6e151c09950c2f01ee706dec01794d65c59
Client failed to read packet PartialReadError: Read error for undefined : Missing characters in string, found size is 102 expected size was 184
    at new ExtendableError (/workspace/mcpeBOT/node_modules/protodef/src/utils.js:63:13)
    at new PartialReadError (/workspace/mcpeBOT/node_modules/protodef/src/utils.js:70:5)
    at Object.string (eval at compile (/workspace/mcpeBOT/node_modules/protodef/src/compiler.js:258:12), <anonymous>:4130:15)
    at Object.packet_animate_entity (eval at compile (/workspace/mcpeBOT/node_modules/protodef/src/compiler.js:258:12), <anonymous>:3739:69)
    at eval (eval at compile (/workspace/mcpeBOT/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1711:68)
    at mcpe_packet (eval at compile (/workspace/mcpeBOT/node_modules/protodef/src/compiler.js:258:12), <anonymous>:1738:9)
    at CompiledProtodef.read (/workspace/mcpeBOT/node_modules/protodef/src/compiler.js:70:12)
    at e.message (/workspace/mcpeBOT/node_modules/protodef/src/compiler.js:111:49)
    at tryCatch (/workspace/mcpeBOT/node_modules/protodef/src/utils.js:50:16)
    at CompiledProtodef.parsePacketBuffer (/workspace/mcpeBOT/node_modules/protodef/src/compiler.js:111:29) {
  partialReadError: true
}
terminate called after throwing an instance of 'Napi::Error'
  what():  Read error for undefined : Missing characters in string, found size is 102 expected size was 184
Aborted (core dumped)

**Comment by extremeheat** [comment]
Confirmed, related to https://github.com/Sandertv/gophertunnel/commit/9e5b27acb2bb8f60eaa1ff3a9804b185e3768d9b
