### ISSUE TITLE
How to use client.js example with PocketMine-MP docker image

### ISSUE THREAD

**Issue by kfern** [PrismarineJS/bedrock-protocol#26]
Hi, my first issue on pmp so first of all thanks everyone involved, love the work you've done!

I'm trying to use client.js example with PocketMine-MP docker image with validation error result. What is a right way to do this?

> $ docker run -d -p 19132:19132/udp --name minecraft_ini cscheide/pocketmine-mp:3.3.2
> $ docker logs minecraft_ini
> 

[21:06:00] [Server thread/INFO]: Loading pocketmine.yml...
[21:06:00] [Server thread/INFO]: Selected English (eng) as the base language
[21:06:00] [Server thread/INFO]: Loading server properties...
[21:06:00] [Server thread/INFO]: Starting Minecraft: Bedrock Edition server version v1.7.0
[21:06:00] [Server thread/NOTICE]: Online mode is enabled. The server will verify that players are authenticated to Xbox Live.
[21:06:00] [Server thread/NOTICE]: To disable authentication, set "xbox-auth" to "false" in server.properties.
[21:06:00] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[21:06:00] [Server thread/INFO]: This server is running PocketMine-MP version 3.3.2
[21:06:00] [Server thread/INFO]: PocketMine-MP is distributed under the LGPL License
[21:06:00] [Server thread/INFO]: Loading resource packs...
[21:06:00] [Server thread/NOTICE]: Level "world" not found
[21:06:00] [Server thread/INFO]: Preparing level "world"
[21:06:00] [Server thread/NOTICE]: Spawn terrain for level "world" is being generated in the background
[21:06:00] [Server thread/INFO]: Starting GS4 status listener
[21:06:00] [Server thread/INFO]: Setting query port to 19132
[21:06:00] [Server thread/INFO]: Query running on 0.0.0.0:19132
[21:06:00] [Server thread/INFO]: Default game type: Creative Mode
[21:06:00] [Server thread/INFO]: Done (0.482s)! For help, type "help" or "?"

When I run client.js I have an validation error:

> $ node client.js [docker-machine actual ip] 19132 kfern

```
{
  "keyword": "enum",
  "dataPath": "",
  "schemaPath": "#/oneOf/0/enum",
  "params": {
    "allowedValues": [
      "native"
    ]
  },
  "message": "should be equal to one of the allowed values",
  "schema": [
    "native"
  ],
  "parentSchema": {
    "enum": [
      "native"
    ]
  },
  "data": [
    "array",
    {
      "countType": "i8",
      "type": [
        "container",
        {
          "name": "cost",
          "type": "i32"
        },
        {
          "name": "enchantments",
          "type": [
            "array",
            {
              "countType": "i8",
              "type": [
                "container",
                {
                  "name": "id",
                  "type": "i32"
                },
                {
                  "name": "level",
                  "id": "i32"
                }
              ]
            }
          ]
        },
        {
          "name": "name",
          "type": "string"
        }
      ]
    }
  ]
}

```
/home/kfern/pmp/node_modules/protodef-validator/index.js:80
      throw new Error("validation error");
      ^

Error: validation error
    at Validator.validateType (/home/kfern/pmp/node_modules/protodef-validator/index.js:80:13)
    at Object.keys.forEach (/home/kfern/pmp/node_modules/protodef/src/protodef.js:100:26)
    at Array.forEach (<anonymous>)
    at ProtoDef.addTypes (/home/kfern/pmp/node_modules/protodef/src/protodef.js:98:26)
    at new Client (/home/kfern/pmp/node_modules/raknet/src/client.js:29:11)
    at Object.createClient (/home/kfern/pmp/node_modules/raknet/src/createClient.js:22:18)
    at Object.createClient (/home/kfern/pmp/node_modules/pocket-minecraft-protocol/src/createClient.js:22:21)
    at Object.<anonymous> (/home/kfern/pmp/client.js:8:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)

**Comment by rom1504** [comment]
The protocol.json seems to be missing definition of some native type.

This lib only works for some old version of pocket Minecraft, and only
partially.

So if you want to use that, it'll have to be in a contributor setting, ie
fix it.

**Comment by kfern** [comment]
Thanks. This sounds big and I'm new in Minecraft dev world.
