### ISSUE TITLE
Can't run on repl.it

### ISSUE THREAD

**Issue by the-glitch69** [PrismarineJS/bedrock-protocol#363]
When i try to run this code on replit it got error.

```
/home/runner/test/node_modules/bedrock-protocol/src/rak.js:61
    }, timeout, () => { throw new RakTimeout('Ping timed out') })
                              ^

RakTimeout [Error]: Ping timed out
    at /home/runner/test/node_modules/bedrock-protocol/src/rak.js:61:31
    at waitFor (/home/runner/test/node_modules/bedrock-protocol/src/datatypes/util.js:30:32)
Emitted 'error' event on Client instance at:


Node.js v18.12.1
repl process died unexpectedly: exit status 1
```

i try so many thing but couldn't find the solution. But when i run directly from my pc it work perfectly fine.

And this is the code that i try on replit.

```
const bedrock = require('bedrock-protocol')
const client = bedrock.createClient({
  host: 'myserver address',   // optional
  port: 16875,         // optional, default 19132
  username: 'test',   // the username you want to join as, optional if online mode
  offline: true       // optional, default false. if true, do not login with Xbox Live. You will not be asked to sign-in if set to true.
})

client.on('text', (packet) => { // Listen for chat messages from the server and echo them back.
  if (packet.source_name != client.username) {
    client.queue('text', {
      type: 'chat', needs_translation: false, source_name: client.username, xuid: '', platform_chat_id: '',
      message: `${packet.source_name} said: ${packet.message} on ${new Date().toLocaleString()}`
    })
  }
})

const { ping } = require('bedrock-protocol')
ping({ host: 'myserver address', port: 16875 }).then(res => {
  console.log(res)
})
```

**Comment by extremeheat** [comment]
This is not an issue with bedrock-protocol. You need to talk to Replit support, or use a proper hosting service if you cannot do so locally.

Related: https://replit.com/talk/ask/How-do-Ports-Work-in-repl/52877, https://replit.com/talk/ask/cannot-connect-to-UDP-socket/138974
