### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by Kibishan** [PrismarineJS/bedrock-protocol#72]
I am not good at coding with protocol and i have this error using the ping.js in your example.

internal/modules/cjs/loader.js:303
      throw err;
      ^

Error: Cannot find module '/home/runner/MCPEbot/node_modules/bedrock-protocol/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:295:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:508:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/MCPEbot/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/home/runner/MCPEbot/node_modules/bedrock-protocol/package.json',
  requestPath: 'bedrock-protocol'
}

**Comment by TheBlueBurger** [comment]
What command are you using to run it?

**Comment by Kibishan** [comment]
node index.js (thats where is my code)

**Comment by extremeheat** [comment]
You need to install from git for now, the npm release hasn’t been updated,

npm i prismarinejs/bedrock-protocol

**Comment by Kibishan** [comment]
oh ok thanks

**Comment by Kibishan** [comment]
idk if i did something wrong but :

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/prismarinejs/bedrock-provider.git
npm ERR! 
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-04-21T10_29_40_657Z-debug.log

**Comment by extremeheat** [comment]
Oops, I meant `npm i PrismarineJS/bedrock-protocol`

**Comment by Kibishan** [comment]
it give me this

/rbd/pnpm-volume/1bf3be17-5780-4ffd-ab33-757cf43ce50c/node_modules/.github.com/PrismarineJS/bedrock-protocol/b60fd53ad51bed4405782bab247b6441fa7b5055/node_modules/bedrock-protocol/src/client.js:150
    this.connection?.close()
                    ^
SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/rbd/pnpm-volume/1bf3be17-5780-4ffd-ab33-757cf43ce50c/node_modules/.github.com/PrismarineJS/bedrock-protocol/b60fd53ad51bed4405782bab247b6441fa7b5055/node_modules/bedrock-protocol/index.js:2:6)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)

**Comment by extremeheat** [comment]
Delete your node_modules folder, package-lock.json and run `npm i PrismarineJS/bedrock-protocol`. Also you need node.js 14+.

**Comment by rom1504** [comment]
We need to have the same thing as mineflayer to check node version otherwise we'll get tens of similar issues

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/mineflayer/blob/master/index.js

**Comment by Kibishan** [comment]
Can you give the node module folder with the lastest version please? I dont why but it wont work

**Comment by extremeheat** [comment]
What’s the error ? Need more info to debug. You can install it via Gitpod to play around if you have issues locally. Also, you can join the discord if you need further help.

**Comment by Kibishan** [comment]
https://pastebin.com/gA1bdUHt

**Comment by extremeheat** [comment]
Run `sudo apt install cmake` and try again.

**Comment by Kibishan** [comment]
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'jsp-raknet/listener'
Require stack:
- C:\Users\NAME\Downloads\MCPE\node_modules\bedrock-protocol\src\rak.js
- C:\Users\NAME\Downloads\MCPE\node_modules\bedrock-protocol\src\client.js
- C:\Users\NAME\Downloads\MCPE\node_modules\bedrock-protocol\index.js
- C:\Users\NAME\Downloads\MCPE\test.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\NAME\Downloads\MCPE\node_modules\bedrock-protocol\src\rak.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\NAME\\Downloads\\MCPE\\node_modules\\bedrock-protocol\\src\\rak.js',
    'C:\\Users\\NAME\\Downloads\\MCPE\\node_modules\\bedrock-protocol\\src\\client.js',
    'C:\\Users\\NAME\\Downloads\\MCPE\\node_modules\\bedrock-protocol\\index.js',
    'C:\\Users\\NAME\\Downloads\\MCPE\\test.js'
  ]
}
PS C:\Users\NAME\Downloads\MCPE> npm i jsp-raknet/listener
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/jsp-raknet/listener.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\NAME\AppData\Roaming\npm-cache\_logs\2021-04-21T12_18_52_813Z-debug.log
PS C:\Users\NAME\Downloads\MCPE> sudo apt install cmake
sudo : Le terme «sudo» n'est pas reconnu comme nom d'applet de commande, fonction, fichier de script ou programme exécutable. Vérifiez l'orthographe du nom, ou 
si un chemin d'accès existe, vérifiez que le chemin d'accès est correct et réessayez.
Au caractère Ligne:1 : 1
+ sudo apt install cmake
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (sudo:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Kibishan** [comment]
it give me this after having successfully downloaded the module

**Comment by extremeheat** [comment]
Can you join the discord? What code are you running? Looks like you switched os. The error you’re getting is caused by you missing dependencies. 

Delete the node_modules folder and package-lock.json file. Then run 

npm i prismarinejs/bedrock-protocol 

then copy over the ping example and run it.

**Comment by Kibishan** [comment]
Whats the discord link please?

**Comment by extremeheat** [comment]
https://discord.gg/GsEFRM8 #bedrock room

**Comment by Kibishan** [comment]
Thank you!!
